PREFIX ka: <http://purl.obolibrary.org/obo/GO_0016301>
PREFIX enables: <http://purl.obolibrary.org/obo/RO_0002327>
PREFIX state: <http://geneontology.org/lego/modelstate> 

SELECT ?g ?g2 ?eC ?aC WHERE {
 GRAPH ?g {
   ?e a ?eC .
   ?a a ?aC .
   ?g state: "production"^^xsd:string .
 }
 
 GRAPH ?g2 {
  ?a a ka: .
  ?e enables: ?a 
 }
 FILTER(!regex(str(?g),"_inferred"))

}
LIMIT 100
