- name: build docker image
  hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Update system packages
    apt:
      update_cache: yes
      upgrade: safe
    become: yes

  - name: Checkout repos
    git:
     repo: '{{ repo }}'
     dest: '{{ repo_dir }}'
     version: '{{ branch }}'
     force: yes

  - name: build go-graphstore image
    shell: "docker build -f {{ repo_dir }}/docker/Dockerfile -t '{{ graphstore_image }}' {{ repo_dir }}"
